#!/bin/bash
sudo apt update
sudo apt install -y build-essential

# PYTHON_VERSION=3.9 (optional)
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt update
sudo apt install -y python3.9 python3-pip python3.9-venv
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 9
# sudo update-alternatives --config python3